#!/bin/sh

if [ "$#" -ne 1 ] || [ "$1" == "--help" ]; then
    cat << EOF
Usage: $0 <path to Dockerfile>

Builds an image using the Dockerfile at the specified path and tags the image 
with the path. Do not include "Dockerfile" in the path.

Examples:

1) $0 clion/fedora/cpp-env # Builds a Fedora image for use with CLion
2) $0 clion/emscripten
EOF
    if [ "$1" == "--help" ]; then
        exit 0
    fi

    exit 1
fi

set -x

# Check if podman is available
if command -v podman >/dev/null 2>&1; then
    CONTAINER_TOOL="podman"
else
    CONTAINER_TOOL="docker"
fi

$CONTAINER_TOOL build -t $1 $1